plugins {
    id 'com.android.application'
}

android {
    namespace 'com.questhub.gamepadrepair'
    compileSdk 35

    defaultConfig {
        applicationId 'com.questhub.gamepadrepair.v8'
        minSdk 29
        targetSdk 35
        versionCode 9
        versionName '9.0.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation 'com.github.MuntashirAkon:libadb-android:3.1.1'
    implementation 'com.github.MuntashirAkon:sun-security-android:1.1'
    implementation 'org.conscrypt:conscrypt-android:2.5.3'
    testImplementation 'junit:junit:4.13.2'
}
